### ISSUE TITLE
Crash when stopping PIE during execution of continuation

### ISSUE THREAD

**Issue by markusstephanides** [splash-damage/future-extensions#16]
Hi!

First of all, awesome library, exactly what I needed to make my game more async with nice error handling!

I have a problem though: When I start my game, I load some data from an API and then do the game logic based on the API results. The problem is, that if I stop the game during this process, the game crashes. Do I need to tell Unreal somehow that there is still a lambda/promise pending so that it waits until the execution of the continuation is done and then shuts down?

**Comment by digibob** [comment]
Hi @markusstephanides , sorry for the late reply, only just noticed this here!

I'm aware of the issue but haven't had the time to fix this yet. I'm afraid there is no workaround right now.

**Comment by digibob** [comment]
I have some changes which I will be testing heavily on internal projects which should resolve this issue, and hopefully get this pushed out publicly in a few weeks.
