### ISSUE TITLE
Execution policy ThreadPool test failures in UE5 EA

### ISSUE THREAD

**Issue by jack-smith-jagex** [splash-damage/future-extensions#26]
I've noticed a couple of tests are failing with the latest version in a UE5 Early Access project, but I'm unsure if it's related to project settings or potential engine changes in UE5. The two tests in question are in `FFutureTestSpec_ExecutionPolicy`:

https://github.com/splash-damage/future-extensions/blob/c17b91ef1dafcacc4dce3415974dca037322cea4/Source/Test/Private/ExecutionPolicy.spec.cpp#L108-L142

`FTaskGraphInterface::Get().GetCurrentThreadIfKnown()` is returning `ENamedThreads::AnyBackgroundThreadNormalTask` rather than `ENamedThreads::AnyThread`, and failing the `TestEqual...` cases.

This can be fixed by changing those lines to:

`TestTrue("Executed on the thread pool", (*Expected & ENamedThreads::AnyThread) == ENamedThreads::AnyThread);`

But I just wanted to double check that the behaviour was similar on your end to make sure it's not a project setup issue.

**Comment by digibob** [comment]
@jack-smith-jagex just confirmed that myself, looks we should mask using ThreadIndexMask, not AnyThread though, will be testing that shortly

**Comment by digibob** [comment]
And in fixing that, have spotted that we've broken ThreadPool waiting on previous Future to complete - will fix that too.

**Comment by digibob** [comment]
Resolved with
https://github.com/splash-damage/future-extensions/commit/e44ec0982f658b64b73ffd4fa9029af27f0827cd
