### ISSUE TITLE
Compile Error using Clang in FutureExtensionsTypeTraits.h

### ISSUE THREAD

**Issue by impguard** [splash-damage/future-extensions#36]
I get the following error when compiling using Clang:

```
T:/p4/project/main/MyGame/Plugins/Runtime/ThirdParty/SDFutureExtensions/Source\SDFutureExtensions/Private/FutureExtensionsTypeTraits.h(161,87): error: implicit instantiation of undefined template 'SD::TExpected<void>'
  auto ContinuationFunctorVoidParamTypeHelper(F Func, int, int, ...) -> decltype(Func(ToExpected()), ToExpected());
                                                                                      ^
T:/p4/project/main/MyGame/Plugins/Runtime/ThirdParty/SDFutureExtensions/Source\SDFutureExtensions/Private/FutureExtensionsTypeTraits.h(10,8): note: template is declared here
 class TExpected;
       ^
1 error generated.
```

It seems to be something with the forward declarations of the template types, so it seems to be resolved when adding the import of `ExpectedResult.h` directly in the file `FutureExtensionsTypeTraits.h`. There's a lot of really complex template work done in this library so I'm not sure if this is the safest or most correct change, so raising viz here for folks!

**Comment by digibob** [comment]
There are definitely some issues with the way in which the headers are set up right now, but we do make use of Clang in-house and I haven't seen the issue you have raised. Would it be possible for you to provide an example of your usage that is cause this error to show up?

**Comment by impguard** [comment]
Hmm, here's some pseudocode of essentially how we use it atm:

```
#include "ExpectedFuture.h"

SD::TExpectedFuture<TCustomHttpResponse<FHttpResponsePtr>> FCustomHttpRequest::Send()
{
	TSharedPtr<SD::TExpectedPromise<TCustomHttpResponse<FHttpResponsePtr>>> Promise =
		MakeShared<SD::TExpectedPromise<TCustomHttpResponse<FHttpResponsePtr>>>();

	FCustomOnRequestSuccess OnSuccess;
	OnSuccess.AddLambda([Promise](const FHttpResponsePtr Response)
	{
	        // TCustomHttpResponse can be built from a response or a standard error
		Promise->SetValue(Response);
	});

	FCustomOnRequestError OnError;
	OnError.AddLambda([Promise](const FStandardError& Error)
	{
		// TCustomHttpResponse can be built from a response or a standard error
		Promise->SetValue(Error);
	});

        // Essentially sends an HTTP Request
	Send(OnSuccess, OnError);

	return Promise->GetFuture();
}
```

I don't think there's anything particularly fancy. For what it's worth, our changes we've made to the library so far are:

```
// In FutureExtensionsTypeTraits.h
// Copyright(c) Splash Damage. All rights reserved.
#pragma once

#include "Templates/IntegralConstant.h"
#include "Runtime/Launch/Resources/Version.h"
// <Modification> Included ExpectedResult.h header to avoid implicit template instantiation clang compile error
#include "ExpectedResult.h"
// </Modification>
```

This seems to resolve the issue.

**Comment by digibob** [comment]
The library currently expects that you bring it in with
```#include "FutureExtensions.h"```
rather than any of the other headers - this is on my TODO list to investigate properly, but has been low priority.
Doing that should remove the need to modify any of the files.

A small note of the code above too - you don't need to `MakeShared` the promise, as it is internally just a wrapper around a shared pointer itself - copying the promise will still refer to the same object, so it will still be safe to capture by value in the lambdas, though you may need to mark them as mutable.

**Comment by impguard** [comment]
Awesome! Thanks for the info. That did indeed fix things. I didn't really check for a wrapper header. My bad! Thanks!
